#!/usr/bin/env python3
"""
generate_source.py — Tạo KeyChecker.m từ config
Chạy bởi GitHub Actions workflow
"""
import argparse, sys

def make_source(verify_url, countdown, cache_key, kc_service):
    cache_str = "YES" if str(cache_key).lower() == "true" else "NO"
    return f"""\
/*  KeyChecker.dylib — generated by generate_source.py
 *  verify_url : {verify_url}
 *  countdown  : {countdown}s
 *  cache_key  : {cache_str}
 */
#import <UIKit/UIKit.h>
#import <Foundation/Foundation.h>
#import <Security/Security.h>
#import <objc/runtime.h>

static NSString *const kVerifyURL       = @"{verify_url}";
static NSString *const kKeychainKey     = @"saved_key";
static NSString *const kKeychainService = @"{kc_service}";
static const NSInteger  kCountdownSec   = {countdown};
static const BOOL       kCacheKey       = {cache_str};

// ── Keychain ─────────────────────────────────────────────────────────────────
static NSString *KeychainLoad(void) {{
    NSDictionary *q = @{{
        (__bridge id)kSecClass:       (__bridge id)kSecClassGenericPassword,
        (__bridge id)kSecAttrService: kKeychainService,
        (__bridge id)kSecAttrAccount: kKeychainKey,
        (__bridge id)kSecReturnData:  @YES,
        (__bridge id)kSecMatchLimit:  (__bridge id)kSecMatchLimitOne,
    }};
    CFTypeRef r = NULL;
    if (SecItemCopyMatching((__bridge CFDictionaryRef)q, &r) == errSecSuccess && r) {{
        NSData *d = (__bridge_transfer NSData *)r;
        return [[NSString alloc] initWithData:d encoding:NSUTF8StringEncoding];
    }}
    return nil;
}}
static void KeychainSave(NSString *key) {{
    NSData *d = [key dataUsingEncoding:NSUTF8StringEncoding];
    NSDictionary *del = @{{
        (__bridge id)kSecClass:       (__bridge id)kSecClassGenericPassword,
        (__bridge id)kSecAttrService: kKeychainService,
        (__bridge id)kSecAttrAccount: kKeychainKey,
    }};
    SecItemDelete((__bridge CFDictionaryRef)del);
    NSDictionary *add = @{{
        (__bridge id)kSecClass:            (__bridge id)kSecClassGenericPassword,
        (__bridge id)kSecAttrService:      kKeychainService,
        (__bridge id)kSecAttrAccount:      kKeychainKey,
        (__bridge id)kSecValueData:        d,
        (__bridge id)kSecAttrAccessible:   (__bridge id)kSecAttrAccessibleAfterFirstUnlock,
    }};
    SecItemAdd((__bridge CFDictionaryRef)add, NULL);
}}
static void KeychainDelete(void) {{
    NSDictionary *del = @{{
        (__bridge id)kSecClass:       (__bridge id)kSecClassGenericPassword,
        (__bridge id)kSecAttrService: kKeychainService,
        (__bridge id)kSecAttrAccount: kKeychainKey,
    }};
    SecItemDelete((__bridge CFDictionaryRef)del);
}}

// ── Network verify ───────────────────────────────────────────────────────────
static void VerifyKey(NSString *key, void(^onOK)(void), void(^onFail)(NSString*)) {{
    NSURL *url = [NSURL URLWithString:kVerifyURL];
    NSMutableURLRequest *req = [NSMutableURLRequest requestWithURL:url
        cachePolicy:NSURLRequestReloadIgnoringCacheData timeoutInterval:15.0];
    req.HTTPMethod = @"POST";
    [req setValue:@"application/json" forHTTPHeaderField:@"Content-Type"];
    NSString *idfv = [[[UIDevice currentDevice] identifierForVendor] UUIDString] ?: @"unknown";
    NSData *body = [NSJSONSerialization dataWithJSONObject:@{{@"key":key, @"device_id":idfv}}
                                                   options:0 error:nil];
    req.HTTPBody = body;
    [[[NSURLSession sharedSession] dataTaskWithRequest:req
        completionHandler:^(NSData *data, NSURLResponse *r, NSError *e) {{
        dispatch_async(dispatch_get_main_queue(), ^{{
            if (e || !data) {{
                if (onFail) onFail(e.localizedDescription ?: @"L\u1ed7i m\u1ea1ng");
                return;
            }}
            NSDictionary *obj = [NSJSONSerialization JSONObjectWithData:data options:0 error:nil];
            if ([obj[@"success"] boolValue]) {{
                if (onOK) onOK();
            }} else {{
                NSString *msg = obj[@"message"] ?: obj[@"error"] ?: @"Key kh\u00f4ng h\u1ee3p l\u1ec7";
                if (onFail) onFail(msg);
            }}
        }});
    }}] resume];
}}

// ═══════════════════════════════════════════════════════════════════════════
//  UI
// ═══════════════════════════════════════════════════════════════════════════
@interface KCWindow : UIWindow @end
@implementation KCWindow @end

@interface KeyCheckerVC : UIViewController <UITextFieldDelegate>
@property (nonatomic, strong) UITextField              *keyField;
@property (nonatomic, strong) UIButton                 *verifyBtn;
@property (nonatomic, strong) UILabel                  *timerLabel;
@property (nonatomic, strong) UILabel                  *statusLabel;
@property (nonatomic, strong) UIActivityIndicatorView  *spinner;
@property (nonatomic, strong) NSTimer                  *cdTimer;
@property (nonatomic, assign) NSInteger                 timeLeft;
@property (nonatomic, assign) BOOL                      verifying;
@end

@implementation KeyCheckerVC

- (void)viewDidLoad {{
    [super viewDidLoad];
    [self buildUI];
    self.timeLeft = kCountdownSec;
    [self updateTimerLabel];
    self.cdTimer = [NSTimer scheduledTimerWithTimeInterval:1.0
                    target:self selector:@selector(tick) userInfo:nil repeats:YES];
}}

- (BOOL)isModalInPresentation               {{ return YES; }}
- (UIModalPresentationStyle)modalPresentationStyle {{ return UIModalPresentationFullScreen; }}
- (UIStatusBarStyle)preferredStatusBarStyle {{ return UIStatusBarStyleLightContent; }}
- (void)viewDidAppear:(BOOL)a               {{ [super viewDidAppear:a]; self.modalInPresentation = YES; }}

// ── Build UI ─────────────────────────────────────────────────────────────────
- (void)buildUI {{
    // Blur background
    UIBlurEffect *blur = [UIBlurEffect effectWithStyle:UIBlurEffectStyleSystemUltraThinMaterialDark];
    UIVisualEffectView *bg = [[UIVisualEffectView alloc] initWithEffect:blur];
    bg.frame = self.view.bounds;
    bg.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
    [self.view addSubview:bg];

    // Card
    UIView *card = [[UIView alloc] init];
    card.translatesAutoresizingMaskIntoConstraints = NO;
    card.backgroundColor = [UIColor colorWithRed:.10 green:.10 blue:.15 alpha:.97];
    card.layer.cornerRadius  = 22;
    card.layer.shadowColor   = UIColor.blackColor.CGColor;
    card.layer.shadowOpacity = .55;
    card.layer.shadowRadius  = 20;
    card.layer.shadowOffset  = CGSizeMake(0, 8);
    [self.view addSubview:card];

    // Icon
    UILabel *ico = [UILabel new];
    ico.text = @"\\U0001F510";
    ico.font = [UIFont systemFontOfSize:48];
    ico.textAlignment = NSTextAlignmentCenter;
    ico.translatesAutoresizingMaskIntoConstraints = NO;
    [card addSubview:ico];

    // Title
    UILabel *title = [UILabel new];
    title.text = @"X\u00e1c Th\u1ef1c Key";
    title.font = [UIFont systemFontOfSize:22 weight:UIFontWeightBold];
    title.textColor = UIColor.whiteColor;
    title.textAlignment = NSTextAlignmentCenter;
    title.translatesAutoresizingMaskIntoConstraints = NO;
    [card addSubview:title];

    // Subtitle
    UILabel *sub = [UILabel new];
    sub.text = @"Nh\u1eadp key \u0111\u1ec3 ti\u1ebfp t\u1ee5c s\u1eed d\u1ee5ng";
    sub.font = [UIFont systemFontOfSize:13];
    sub.textColor = [UIColor colorWithWhite:.55 alpha:1];
    sub.textAlignment = NSTextAlignmentCenter;
    sub.translatesAutoresizingMaskIntoConstraints = NO;
    [card addSubview:sub];

    // Timer
    UILabel *tl = [UILabel new];
    tl.font = [UIFont monospacedDigitSystemFontOfSize:32 weight:UIFontWeightMedium];
    tl.textColor = [UIColor colorWithRed:.3 green:.85 blue:1 alpha:1];
    tl.textAlignment = NSTextAlignmentCenter;
    tl.translatesAutoresizingMaskIntoConstraints = NO;
    [card addSubview:tl];
    self.timerLabel = tl;

    UILabel *tDesc = [UILabel new];
    tDesc.text = @"\u23f1 Th\u1eddi gian nh\u1eadp key";
    tDesc.font = [UIFont systemFontOfSize:11];
    tDesc.textColor = [UIColor colorWithWhite:.4 alpha:1];
    tDesc.textAlignment = NSTextAlignmentCenter;
    tDesc.translatesAutoresizingMaskIntoConstraints = NO;
    [card addSubview:tDesc];

    // Divider
    UIView *div = [UIView new];
    div.backgroundColor = [UIColor colorWithWhite:.2 alpha:1];
    div.translatesAutoresizingMaskIntoConstraints = NO;
    [card addSubview:div];

    // TextField
    UITextField *tf = [UITextField new];
    tf.attributedPlaceholder = [[NSAttributedString alloc]
        initWithString:@"Nh\u1eadp key c\u1ee7a b\u1ea1n..."
            attributes:@{{NSForegroundColorAttributeName:[UIColor colorWithWhite:.3 alpha:1]}}];
    tf.textColor = UIColor.whiteColor;
    tf.font = [UIFont monospacedSystemFontOfSize:15 weight:UIFontWeightRegular];
    tf.backgroundColor = [UIColor colorWithRed:.16 green:.16 blue:.22 alpha:1];
    tf.layer.cornerRadius = 12;
    tf.layer.borderWidth  = 1;
    tf.layer.borderColor  = [UIColor colorWithWhite:.22 alpha:1].CGColor;
    tf.autocorrectionType = UITextAutocorrectionTypeNo;
    tf.autocapitalizationType = UITextAutocapitalizationTypeNone;
    tf.returnKeyType = UIReturnKeyDone;
    tf.textAlignment = NSTextAlignmentCenter;
    tf.leftView  = [[UIView alloc] initWithFrame:CGRectMake(0,0,14,0)];
    tf.leftViewMode = UITextFieldViewModeAlways;
    tf.delegate  = self;
    tf.translatesAutoresizingMaskIntoConstraints = NO;
    [card addSubview:tf];
    self.keyField = tf;

    // Status label
    UILabel *sl = [UILabel new];
    sl.text = @"";
    sl.font = [UIFont systemFontOfSize:12];
    sl.numberOfLines = 2;
    sl.textAlignment = NSTextAlignmentCenter;
    sl.translatesAutoresizingMaskIntoConstraints = NO;
    [card addSubview:sl];
    self.statusLabel = sl;

    // Verify button
    UIButton *btn = [UIButton buttonWithType:UIButtonTypeSystem];
    [btn setTitle:@"\u2705  X\u00e1c Nh\u1eadn Key" forState:UIControlStateNormal];
    btn.titleLabel.font = [UIFont systemFontOfSize:16 weight:UIFontWeightSemibold];
    [btn setTitleColor:UIColor.whiteColor forState:UIControlStateNormal];
    btn.backgroundColor = [UIColor colorWithRed:.22 green:.42 blue:.95 alpha:1];
    btn.layer.cornerRadius = 14;
    btn.translatesAutoresizingMaskIntoConstraints = NO;
    [btn addTarget:self action:@selector(tappedVerify) forControlEvents:UIControlEventTouchUpInside];
    [card addSubview:btn];
    self.verifyBtn = btn;

    // Spinner
    UIActivityIndicatorView *sp;
    if (@available(iOS 13,*))
        sp = [[UIActivityIndicatorView alloc] initWithActivityIndicatorStyle:UIActivityIndicatorViewStyleMedium];
    else
        sp = [[UIActivityIndicatorView alloc] initWithActivityIndicatorStyle:UIActivityIndicatorViewStyleWhite];
    sp.color = UIColor.whiteColor;
    sp.hidesWhenStopped = YES;
    sp.translatesAutoresizingMaskIntoConstraints = NO;
    [btn addSubview:sp];
    self.spinner = sp;

    // ── Constraints ───────────────────────────────────────────────────────────
    [NSLayoutConstraint activateConstraints:@[
        [card.centerXAnchor constraintEqualToAnchor:self.view.centerXAnchor],
        [card.centerYAnchor constraintEqualToAnchor:self.view.centerYAnchor constant:-20],
        [card.widthAnchor   constraintEqualToConstant:310],

        [ico.topAnchor      constraintEqualToAnchor:card.topAnchor constant:28],
        [ico.centerXAnchor  constraintEqualToAnchor:card.centerXAnchor],

        [title.topAnchor    constraintEqualToAnchor:ico.bottomAnchor constant:8],
        [title.leadingAnchor  constraintEqualToAnchor:card.leadingAnchor  constant:20],
        [title.trailingAnchor constraintEqualToAnchor:card.trailingAnchor constant:-20],

        [sub.topAnchor      constraintEqualToAnchor:title.bottomAnchor constant:5],
        [sub.leadingAnchor    constraintEqualToAnchor:card.leadingAnchor  constant:20],
        [sub.trailingAnchor   constraintEqualToAnchor:card.trailingAnchor constant:-20],

        [tl.topAnchor       constraintEqualToAnchor:sub.bottomAnchor constant:18],
        [tl.centerXAnchor   constraintEqualToAnchor:card.centerXAnchor],

        [tDesc.topAnchor    constraintEqualToAnchor:tl.bottomAnchor constant:3],
        [tDesc.centerXAnchor constraintEqualToAnchor:card.centerXAnchor],

        [div.topAnchor      constraintEqualToAnchor:tDesc.bottomAnchor constant:16],
        [div.leadingAnchor    constraintEqualToAnchor:card.leadingAnchor  constant:20],
        [div.trailingAnchor   constraintEqualToAnchor:card.trailingAnchor constant:-20],
        [div.heightAnchor   constraintEqualToConstant:1],

        [tf.topAnchor       constraintEqualToAnchor:div.bottomAnchor constant:16],
        [tf.leadingAnchor     constraintEqualToAnchor:card.leadingAnchor  constant:20],
        [tf.trailingAnchor    constraintEqualToAnchor:card.trailingAnchor constant:-20],
        [tf.heightAnchor    constraintEqualToConstant:50],

        [sl.topAnchor       constraintEqualToAnchor:tf.bottomAnchor constant:8],
        [sl.leadingAnchor     constraintEqualToAnchor:card.leadingAnchor  constant:20],
        [sl.trailingAnchor    constraintEqualToAnchor:card.trailingAnchor constant:-20],
        [sl.heightAnchor    constraintEqualToConstant:32],

        [btn.topAnchor      constraintEqualToAnchor:sl.bottomAnchor constant:6],
        [btn.leadingAnchor    constraintEqualToAnchor:card.leadingAnchor  constant:20],
        [btn.trailingAnchor   constraintEqualToAnchor:card.trailingAnchor constant:-20],
        [btn.heightAnchor   constraintEqualToConstant:52],

        [sp.centerYAnchor   constraintEqualToAnchor:btn.centerYAnchor],
        [sp.trailingAnchor  constraintEqualToAnchor:btn.trailingAnchor constant:-16],

        [card.bottomAnchor  constraintEqualToAnchor:btn.bottomAnchor constant:28],
    ]];
}}

// ── Timer ─────────────────────────────────────────────────────────────────────
- (void)tick {{
    if (self.verifying) return;
    self.timeLeft--;
    [self updateTimerLabel];
    if (self.timeLeft <= 0) {{
        [self.cdTimer invalidate];
        [self doExit:@"\u23f1 H\u1ebft th\u1eddi gian! M\u1edf l\u1ea1i \u1ee9ng d\u1ee5ng v\u00e0 nh\u1eadp key."];
    }}
}}
- (void)updateTimerLabel {{
    NSInteger s = self.timeLeft;
    self.timerLabel.text = [NSString stringWithFormat:@"%02ld:%02ld", s/60, s%60];
    if (s <= 10)
        self.timerLabel.textColor = [UIColor colorWithRed:1 green:.25 blue:.25 alpha:1];
    else if (s <= 20)
        self.timerLabel.textColor = [UIColor colorWithRed:1 green:.75 blue:0  alpha:1];
    else
        self.timerLabel.textColor = [UIColor colorWithRed:.3 green:.85 blue:1 alpha:1];
}}

// ── Verify ────────────────────────────────────────────────────────────────────
- (void)tappedVerify {{
    NSString *key = [self.keyField.text
        stringByTrimmingCharactersInSet:NSCharacterSet.whitespaceAndNewlineCharacterSet];
    if (!key.length) {{
        [self showStatus:@"\u26a0\ufe0f Vui l\u00f2ng nh\u1eadp key" isErr:YES];
        [self shakeView:self.keyField];
        return;
    }}
    [self setVerifyingState:YES];
    VerifyKey(key, ^{{
        // ✅ Success
        [self.cdTimer invalidate];
        if (kCacheKey) KeychainSave(key);
        [self showStatus:@"\u2705 Key h\u1ee3p l\u1ec7! \u0110ang m\u1edf..." isErr:NO];
        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(.8*NSEC_PER_SEC)),
                       dispatch_get_main_queue(), ^{{
            objc_setAssociatedObject(UIApplication.sharedApplication,
                                     "kcWin", nil, OBJC_ASSOCIATION_RETAIN_NONATOMIC);
        }});
    }}, ^(NSString *reason) {{
        // ❌ Fail
        [self setVerifyingState:NO];
        KeychainDelete();
        [self showStatus:[NSString stringWithFormat:@"\u274c %@", reason] isErr:YES];
        [self shakeView:self.keyField];
        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(1.5*NSEC_PER_SEC)),
                       dispatch_get_main_queue(), ^{{ [self doExit:reason]; }});
    }});
}}

- (void)setVerifyingState:(BOOL)on {{
    self.verifying         = on;
    self.verifyBtn.enabled = !on;
    self.keyField.enabled  = !on;
    on ? [self.spinner startAnimating] : [self.spinner stopAnimating];
    [UIView animateWithDuration:.2 animations:^{{ self.verifyBtn.alpha = on ? .6 : 1; }}];
    if (on) [self showStatus:@"\u23f3 \u0110ang x\u00e1c th\u1ef1c..." isErr:NO];
}}

- (void)showStatus:(NSString*)msg isErr:(BOOL)e {{
    self.statusLabel.text = msg;
    self.statusLabel.textColor = e
        ? [UIColor colorWithRed:1 green:.3  blue:.3  alpha:1]
        : [UIColor colorWithRed:.3 green:.9 blue:.5  alpha:1];
}}

- (void)doExit:(NSString*)reason {{
    UIAlertController *a = [UIAlertController
        alertControllerWithTitle:@"Truy c\u1eadp b\u1ecb t\u1eeb ch\u1ed1i"
        message:reason preferredStyle:UIAlertControllerStyleAlert];
    [a addAction:[UIAlertAction actionWithTitle:@"Tho\u00e1t"
        style:UIAlertActionStyleDestructive handler:^(UIAlertAction *_) {{ exit(0); }}]];
    [self presentViewController:a animated:YES completion:nil];
}}

- (void)shakeView:(UIView*)v {{
    CAKeyframeAnimation *a = [CAKeyframeAnimation animationWithKeyPath:@"transform.translation.x"];
    a.timingFunction = [CAMediaTimingFunction functionWithName:kCAMediaTimingFunctionLinear];
    a.duration = .4;
    a.values   = @[@(-8),@(8),@(-6),@(6),@(-4),@(4),@0];
    [v.layer addAnimation:a forKey:@"shake"];
}}

- (BOOL)textFieldShouldReturn:(UITextField*)tf {{ [self tappedVerify]; return YES; }}
- (void)touchesBegan:(NSSet*)t withEvent:(UIEvent*)e {{ [self.view endEditing:YES]; }}
@end

// ── Entry point ───────────────────────────────────────────────────────────────
static void ShowKeyChecker(void);

static void ShowKeyChecker(void) {{
    dispatch_async(dispatch_get_main_queue(), ^{{
        if (kCacheKey) {{
            NSString *cached = KeychainLoad();
            if (cached.length) {{
                VerifyKey(cached,
                    ^{{ NSLog(@"[KC] Cached key OK"); }},
                    ^(NSString *r) {{ KeychainDelete(); ShowKeyChecker(); }});
                return;
            }}
        }}
        UIWindowScene *scene = nil;
        if (@available(iOS 13,*)) {{
            for (UIScene *s in UIApplication.sharedApplication.connectedScenes)
                if ([s isKindOfClass:UIWindowScene.class] &&
                    s.activationState == UISceneActivationStateForegroundActive)
                {{ scene = (UIWindowScene*)s; break; }}
        }}
        KCWindow *win;
        if (@available(iOS 13,*))
            win = scene ? [[KCWindow alloc] initWithWindowScene:scene]
                        : [[KCWindow alloc] initWithFrame:UIScreen.mainScreen.bounds];
        else
            win = [[KCWindow alloc] initWithFrame:UIScreen.mainScreen.bounds];

        win.windowLevel = UIWindowLevelAlert + 100;
        win.backgroundColor = UIColor.clearColor;
        win.rootViewController = [[KeyCheckerVC alloc] init];
        objc_setAssociatedObject(UIApplication.sharedApplication,
                                  "kcWin", win, OBJC_ASSOCIATION_RETAIN_NONATOMIC);
        [win makeKeyAndVisible];
    }});
}}

__attribute__((constructor))
static void KC_Init(void) {{
    NSLog(@"[KeyChecker] dylib loaded ✓");
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(.5*NSEC_PER_SEC)),
                   dispatch_get_main_queue(), ^{{ ShowKeyChecker(); }});
}}
"""

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--verify-url",  default="https://bucac.onrender.com/api/verify-key")
    parser.add_argument("--countdown",   default="30")
    parser.add_argument("--cache-key",   default="true")
    parser.add_argument("--kc-service",  default="com.keychecker.app")
    parser.add_argument("--output",      default="KeyChecker.m")
    args = parser.parse_args()

    src = make_source(args.verify_url, args.countdown, args.cache_key, args.kc_service)
    with open(args.output, "w", encoding="utf-8") as f:
        f.write(src)
    print(f"Generated {args.output} ({src.count(chr(10))} lines)")
